### ISSUE TITLE
Weekend Wish List 

### ISSUE THREAD

**Issue by alexandriawhite** [devkjoon/krn#44]
Hamburger icon
- Add functionality 

Homepage: 
- Logout button

Workout and Exercise
- Add path on homepage
- Cleanup CSS

APIs
- Research 
- Try to get the APIs connected

Fun Sprinkles (research/ maybe create handlebars placeholders):
- Water tracker
- Calorie tracker 
- Calendar

**Comment by alexandriawhite** [comment]
Update as of 1/28: 
- Researched APIs
- Got APIs connected
- Need to work on code for APIs

**Comment by devkjoon** [comment]
Hamburger icon is functional

**Comment by devkjoon** [comment]
CSS is cleaned up

**Comment by alexandriawhite** [comment]
Logout button working 
Nav bar: hard coded the path for BMI page in welcome and homepage handlebars. Will need to update once I get my code working in bmiinputs
